### PR TITLE
Update .eleventy.js

### PR DESCRIPTION
**Pull request by rcopstein**
Turns the Nujuck-only shortcode into a universal shortcode

### CODE REVIEW

**Comment by LukeStorry** [comment]
@takanorip Please can we merge this PR, as it would enable me to use your great plugin for pug as well as nunjucks templates

**Review by takanorip — APPROVED** [review]
Looks good to me!

**Comment by takanorip** [comment]
@rcopstein Sorry, I wasn't aware of this PR.
I think it's a very good change and I'll merge it.
Thanks for making the PR.

@LukeStorry Thank you so much for the reminder.

**Comment by rcopstein** [comment]
@takanorip, @LukeStorry Thank you for looking into this! Happy to help! 😄

**Pull request merged**
